/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MotionPreviewRouteImport } from './routes/motion-preview'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated.projects.new'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated.projects.$id'
import { Route as AuthenticatedProjectsIdPreviewRouteImport } from './routes/_authenticated.projects.$id.preview'

const MotionPreviewRoute = MotionPreviewRouteImport.update({
  id: '/motion-preview',
  path: '/motion-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedProjectsIdPreviewRoute =
  AuthenticatedProjectsIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motion-preview': typeof MotionPreviewRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motion-preview': typeof MotionPreviewRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/motion-preview': typeof MotionPreviewRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/motion-preview'
    | '/billing'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/motion-preview'
    | '/billing'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/motion-preview'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/new'
    | '/_authenticated/projects/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  MotionPreviewRoute: typeof MotionPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/motion-preview': {
      id: '/motion-preview'
      path: '/motion-preview'
      fullPath: '/motion-preview'
      preLoaderRoute: typeof MotionPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$id/preview': {
      id: '/_authenticated/projects/$id/preview'
      path: '/preview'
      fullPath: '/projects/$id/preview'
      preLoaderRoute: typeof AuthenticatedProjectsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedProjectsIdRoute
    }
  }
}

interface AuthenticatedProjectsIdRouteChildren {
  AuthenticatedProjectsIdPreviewRoute: typeof AuthenticatedProjectsIdPreviewRoute
}

const AuthenticatedProjectsIdRouteChildren: AuthenticatedProjectsIdRouteChildren =
  {
    AuthenticatedProjectsIdPreviewRoute: AuthenticatedProjectsIdPreviewRoute,
  }

const AuthenticatedProjectsIdRouteWithChildren =
  AuthenticatedProjectsIdRoute._addFileChildren(
    AuthenticatedProjectsIdRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRouteWithChildren
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  MotionPreviewRoute: MotionPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
